ALTER TABLE t_reference_voting_vote DROP CONSTRAINT FK_T_REFERENCE_VOTING_VOTE_ON_REFERENCE_VOTING;
ALTER TABLE t_reference DROP CONSTRAINT FK_T_REFERENCE_ON_REFERENCE_VOTING;
DROP TABLE t_reference_voting_vote CASCADE;
DROP TABLE t_reference_voting CASCADE;

ALTER TABLE t_reference ADD CONSTRAINT FK_T_REFERENCE_ON_VOTING
    FOREIGN KEY (reference_voting_id) REFERENCES t_voting (id);