server:
  port: ${SERVER_PORT:9006}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
      expiration: 604800000 # 7 * 24 * 60 * 60 * 1000

spring:
  application:
    name: learning-service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5436/postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    user: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    #      ddl-auto: create-drop
    #      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    pl.app: TRACE