version: '3'

services:
  learning-service-db:
    container_name: 'learning-service-db'
    image: 'bitnami/postgresql:13'
    restart: unless-stopped
    ports:
      - '5436:5432'
    environment:
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
  learning-service:
    container_name: 'learning-service'
    image: ghcr.io/grubeb/learning-service:latest
    ports:
      - '9006:8080'
    environment:
      - SERVER_PORT=8080
      - DATASOURCE_URL=jdbc:postgresql://learning-service-db:5432/postgres
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres

  authorization-service-db:
    container_name: 'authorization-service-db'
    image: 'bitnami/postgresql:13'
    restart: unless-stopped
    ports:
      - '5437:5432'
    environment:
      POSTGRESQL_DATABASE: postgres
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: postgres
  authorization-service:
    container_name: 'authorization-service'
    image: ghcr.io/grubeb/authorization-service:latest
    ports:
      - '9007:8080'
    environment:
      - SERVER_PORT=8080
      - DATASOURCE_URL=jdbc:postgresql://authorization-service-db:5432/postgres
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres

  pgadmin:
    container_name: 'pgadmin'
    image: 'dpage/pgadmin4:7.4'
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pass@word123
    ports:
      - '9050:80'