server:
  port: ${SERVER_PORT:9000}

spring:
  application:
    name: edge-service
  cloud:
    gateway:
      routes:
        - id: authorization-service-route
          uri: http://localhost:9007
          predicates:
            - |
             Path=
              /api/v1/auth/**, 
              /api/v1/users/**, 
              /api/v1/roles/**, 
              /api/v1/permissions/**
        - id: learning-service-route
          uri: http://localhost:9006
          predicates:
            - | 
             Path=
              /api/v1/categories/**, 
              /api/v1/chapters/**, 
              /api/v1/groups/**, 
              /api/v1/group-revisions/**, 
              /api/v1/paths/**, 
              /api/v1/references/**, 
              /api/v1/topics/**, 
              /api/v1/topic-revisions/**

logging:
  level:
    pl.app: TRACE
    org.springframework.cloud.commons.util: DEBUG