name: Create and publish a authorization_service Docker image
on:
  [workflow_dispatch]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: grubeb/authorization-service
  PATH_TO_DOCKERFILE: ./.docker/authorization_service_image/Dockerfile

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -f ${{ env.PATH_TO_DOCKERFILE }} -t ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: publish
        run: |
          docker login -u grubeb -p ${{ secrets.GIT_TOKEN }} ${{ env.REGISTRY }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
