name: Build and publish docker image to Docker Hub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build -f ./.docker/learning_service_image/Dockerfile -t learning-service:latest .
      - name: publish
        run: |
          docker login -u grubeb -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push grubeb/learning-service:latest
